dist: xenial
sudo: required

language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8

before_install:
  - sudo add-apt-repository ppa:jonathonf/ffmpeg-3 -y
  - sudo apt-get update -q
  - sudo apt-get install ffmpeg -y

install:
  - pip install -U tox-travis
  - pip install python-coveralls

script:
  - tox -r

after_success:
  - coveralls

notifications:
  email: false
